name: Generate Release Notes
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release-notes:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release-notes')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: baires/ai-release-notes-action@v1
